bootstrap/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class productsController : Controller
    {
        // GET: products



        public ActionResult products()
        {


            return View();
        }


        public ActionResult laptop()
        {
            return View();
        }

        public ActionResult Tv()
        {
            return View();
        }

        public ActionResult microwave()
        {
            return View();
        }

        public ActionResult Mobile()
        {
            return View();
        }
    }
}

bootstrap/Views/products/Mobile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <div class="jumbotron text-center">
            <h1>
                This is for buying Mobile
            </h1>
            <div>
                <h3>@Html.ActionLink("Homepage", "index", "Home")</h3>
            </div>
            <div>
                <h3>@Html.ActionLink("Productspage", "products", "products")</h3>
            </div>
        </div>
    </div>
</body>
</html>

bootstrap/Views/products/Tv.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <div class="jumbotron text-center">
            <h1>
                This is for buying Tv
            </h1>
            <div>
                <h3>@Html.ActionLink("Homepage", "index", "Home")</h3>
            </div>
            <div>
                <h3>@Html.ActionLink("Productspage", "products", "products")</h3>
            </div>
        </div>
    </div>
</body>
</html>

bootstrap/Views/products/laptop.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <div class="jumbotron text-center">
            <h1>
                This is for buying laptop
            </h1>
            <div>
                <h3>@Html.ActionLink("Homepage", "index", "Home")</h3>
            </div>
            <div>
                <h3>@Html.ActionLink("Productspage", "products", "products")</h3>
            </div>
        </div>
    </div>
</body>
</html>

bootstrap/Views/products/microwave.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <div class="jumbotron text-center">
            <h1>
                This is for buying Microwave
            </h1>
            <div>
                <h3>@Html.ActionLink("Homepage", "index", "Home")</h3>
            </div>
            <div>
                <h3>@Html.ActionLink("Productspage", "products", "products")</h3>
            </div>
        </div>
    </div>
</body>
</html>

bootstrap/Views/products/products.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>

        <div class="jumbotron text-center">
            <h1>
                products
            </h1>
            <div>
                <h2>@Html.ActionLink("laptop", "laptop", "products")</h2>
            </div>
            <div>
                <h2>@Html.ActionLink("Tv", "Tv", "products")</h2>
            </div>
            <div>
                <h2>@Html.ActionLink("Microwave", "Microwave", "products")</h2>
            </div>
            <div>
                <h2>@Html.ActionLink("Mobile", "Mobile", "products")</h2>
            </div>
            <div>
                <h3>@Html.ActionLink("Home page", "index", "Home")</h3>
            </div>
        </div>

    </div>
</body>
</html>