bootstrap/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult About()
        {

            return View();
        }

        public ActionResult Contact()
        {

            return View();
        }
    }
}

bootstrap/Controllers/serviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class serviceController : Controller
    {
        // GET: service

        public ActionResult services()
        {
            return View();
        }
        public ActionResult laptopservice()
        {
            return View();
        }
        public ActionResult Tvservice()
        {
            return View();
        }

        public ActionResult Mobileservice()
        {
            return View();
        }

        public ActionResult microwaveservice()
        {
            return View();
        }
    }
}

bootstrap/Views/Home/About.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <div class="jumbotron text-center">
            <h1>
                This is about us
            </h1>
            <h3>@Html.ActionLink("Home page", "index")</h3>
        </div>
    </div>
</body>
</html>

bootstrap/Views/Home/Contact.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <div class="jumbotron text-center">
            <h1>
                This is contact us
            </h1>
            <h3>@Html.ActionLink("Home page", "index")</h3>
        </div>


    </div>
</body>
</html>

bootstrap/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <div class="jumbotron text-center">

            <h1>Home Page</h1>
            <div class="container">
                <div>
                    <h3>@Html.ActionLink("about us", "about")</h3>

                </div>
                <div>
                    <h3> @Html.ActionLink("contact us", "contact") </h3>

                </div>
            </div>


        </div>
        <div>
            <div class="jumbotron text-center">

                <h1> Products and services </h1>
                <h2>@Html.ActionLink("products", "products", "products")</h2>
                <h2>@Html.ActionLink("services", "services", "service")</h2>


            </div>

        </div>
    </div>
</body>
</html>